application: openmobiledata
version: 1
runtime: python
api_version: 1
default_expiration: "600s"

builtins:
- remote_api: on

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /.*
  script: gspeedometer/main.py
  login: required
